spring:
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://localhost:7433/postgres"
    driver-class: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always

currency-exchange:
  rates-url: "https://api.apilayer.com/exchangerates_data/latest?apikey=ZtmmALl5jsKkIGZn7Kb4fGXaT4iW7z9Z&base={base}"
  exchange-url: "https://api.apilayer.com/exchangerates_data/convert?&amount={amount}&from={from}&to={to}&apikey=ZtmmALl5jsKkIGZn7Kb4fGXaT4iW7z9Z"

mosquitto:
  uri: tcp://localhost:1883
  user: user
  password: 12345678