spring:
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://127.0.0.1:5432/test"
    driver-class: "org.postgresql.Driver"
  jpa:
    show-sql: false

currency-exchange:
  rates-url: "https://api.apilayer.com/exchangerates_data/latest?apikey=ZtmmALl5jsKkIGZn7Kb4fGXaT4iW7z9Z&base={base}"
  exchange-url: "https://api.apilayer.com/exchangerates_data/convert?to={to}&from={from}&amount={amount}&apikey=ZtmmALl5jsKkIGZn7Kb4fGXaT4iW7z9Z"