version: 'v2.13.0'

services:
  db:
    container_name: bankdb
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - 7433:5432
  mosquitto:
   container_name: mqtt
   image: eclipse-mosquitto
   restart: always
   volumes:
     - ./config:/mosquitto/config
     - ./config:/mosquitto/data
     - ./config:/mosquitto/log
   ports:
     - 1883:1883
     - 9001-9001


